name: Push a new tag every 4 hours.

on:
  push:
    branches: [main]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  "0 11-23/4 * * 1-5"

jobs:
  new_tag:

    runs-on: ubuntu-latest
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Generate contrast colors
      id: contrast-colors
      run: |
        COLORS=$(php .github/scripts/color.php)
        echo "::set-output name=bg::$(echo $COLORS | jq -r '.bg')"
        echo "::set-output name=text::$(echo $COLORS | jq -r '.text')"

    - name: Get latest tag
      id: latest-tag
      run: |
        NEW_TAG=$(php .github/scripts/tag.php)
        echo "::set-output name=tag::$(echo $NEW_TAG | jq -r '.tag')"
    
    - name: Test output
      id: test-output
      run: |
        echo "Tag: ${{ steps.latest-tag.outputs.tag }}"
        echo "Background color: ${{ steps.contrast-colors.outputs.bg }}"
        echo "Text color: ${{ steps.contrast-colors.outputs.text }}"

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Auto-update tag: ${{ steps.latest-tag.outputs.tag }}"
        tagging_message: ${{ steps.latest-tag.outputs.tag }}
